/*"accurate",
"ace avenger",
"add health",
"adroit",
"ally dragonblade",
"ally ether shield",
"ally glacial shield",
"ally spirit shield",
"ally stun block",
"ally thermic shield",
"ally volcanic shield",
"amplifier",
"amplify",
"animate skeleton",
"ardent amplifier",
"armor breaker",
"armor piercer",
"astute",
"attentive",
"aura crush",
"bad snowman",
"balance assailant",
"balance boon",
"balance dealer",
"balance eye",
"balance giver",
"balance it",
"balance off",
"balance sniper",
"balance striker",
"balance ward",
"balanceblade",
"balanceblade",
"balancespear",
"batusi",
"berserker",
"best of show",
"big energy",
"big sparky",
"biting cold",
"black mantle",
"black widow",
"blade flurry",
"blade of fire",
"blade of ice",
"blade of life",
"blazing oak",
"blocker",
"boss toad",
"brazen berserker",
"brilliant",
"brown recluse",
"buff minion",
"buff minion",
"bullheaded",
"bulwark",
"button tom",
"calculating",
"calm",
"canny",
"capable",
"careful",
"cautious",
"charm chopper",
"chastisement",
"cheeky",
"clean charm",
"clean ward",
"clock spider",
"cloud o'bugs",
"conviction",
"courageous",
"crafty",
"critical hitter",
"critical striker",
"crystallize",
"cunning",
"cure crusher",
"curse",
"curse giver",
"cycle of life",
"cycle of life",
"dashing",
"death assailant",
"death away",
"death boon",
"death dealer",
"death eye",
"death finder",
"death giver",
"death proof",
"death shield",
"death shot",
"death sniper",
"death striker",
"death trap",
"death ward",
"deathblade",
"deathspear",
"defender",
"defender's rampart",
"dependable",
"determined",
"disarmament",
"dissipate",
"distract",
"dogged",
"dot doctor",
"dragonblade",
"draw power trained",
"drop it",
"durable",
"eager",
"early bird",
"effective",
"effervescent",
"efficient",
"element blade",
"element shield",
"elf on fire",
"empowerment",
"energizing battery",
"entangle",
"epic fishing luck",
"evil eye",
"expert empowerer",
"extra mana",
"fairy friend",
"fearless fortifier",
"feeling weak",
"feinting spell",
"fire assailant",
"fire away",
"fire boon",
"fire dealer",
"fire eye",
"fire giver",
"fire proof",
"fire shield",
"fire shot",
"fire sniper",
"fire striker",
"fire trap",
"fire ward",
"fireblade",
"firespear",
"fishing luck",
"forceful",
"fortify",
"freeze",
"frenzied",
"frozen kraken trained",
"fuel",
"furnace",
"galvanic field",
"gardening pixie",
"gargantuan",
"get sunbird",
"giant",
"gifted",
"go humongo",
"gold miner",
"grand phoenix",
"green thumb",
"guardian wall",
"guiding light",
"healer",
"health boost",
"health bounty",
"health gift",
"healthy",
"heart o'pixie",
"hearty",
"hex",
"hex trained",
"hex trained",
"hexster",
"huge energy",
"ice assailant",
"ice away",
"ice boon",
"ice dealer",
"ice eye",
"ice giver",
"ice proof",
"ice shot",
"ice sniper",
"ice striker",
"ice trap",
"ice ward",
"iceblade",
"icespear",
"incredibly infallible",
"infector",
"intrepid",
"intuitive",
"keen eyes",
"life assailant",
"life away",
"life boon",
"life bringer",
"life eye",
"life fuel",
"life giver",
"life proof",
"life shield",
"life shot",
"life sniper",
"life striker",
"life trap",
"life ward",
"lifeblade",
"lifespear",
"light strike",
"link trained",
"link trained",
"lively",
"magnificent mender",
"mana boost",
"mana bounty",
"mana gift",
"medic",
"mega soothe",
"melt",
"mend minion",
"mender",
"might of myth",
"mighty",
"monstrous",
"mulligan's shuffle",
"myth assailant",
"myth away",
"myth boon",
"myth dealer",
"myth eye",
"myth finder",
"myth finder",
"myth fuel",
"myth giver",
"myth proof",
"myth shield",
"myth shot",
"myth sniper",
"myth striker",
"myth trap",
"myth ward",
"mythblade",
"mythspear",
"no pain no gain",
"pacify",
"pain bringer",
"pain giver",
"perceptive",
"pet rescue",
"pierce train",
"piercemonger",
"pip conserver",
"pip o'plenty",
"pip saver",
"plague",
"plaguebringer",
"power player",
"power taker",
"power up",
"powerful",
"punishment",
"pyromania",
"pyrosaurus rex",
"quench",
"quick witted",
"rage of winter",
"refreshed",
"reinforce",
"relentless",
"reliquary",
"resourceful",
"reveal fish school",
"rugged",
"sap health",
"screen",
"sharp",
"sharp eye",
"sharp shot",
"sleet storm",
"smoke screen",
"snow 'n tell",
"snow heal for you",
"snow shield",
"snowborn",
"spartan",
"spell defying",
"spell proof",
"spirit armor",
"spirit blade",
"spirit shield",
"spirited",
"sprite queen",
"sprite time",
"spritely",
"stalwart",
"steadfast",
"steal blade",
"steal charm",
"steal health",
"steal ward",
"storm assailant",
"storm away",
"storm boon",
"storm dealer",
"storm elemental",
"storm eye",
"storm front",
"storm giver",
"storm proof",
"storm shield",
"storm shot",
"storm sniper",
"storm striker",
"storm tooth",
"storm trap",
"storm ward",
"stormblade",
"stormclaw",
"stormspear",
"strangle",
"strong",
"stun",
"stun recalcitrant",
"stun resistant",
"sturdy",
"subdue",
"sword and shield",
"taunt",
"tenacious",
"the deer knight rises",
"thinkin' cap",
"thunder lizard",
"tick kicker",
"time skip",
"tireless",
"tower shield",
"tranquilize",
"ultra energy",
"unbalance",
"unbalancer",
"unicorn",
"unshakeable",
"unstoppable",
"vampire trained",
"vampire trained",
"vaporize",
"vehement vanquisher",
"vengeance",
"vengeful seraph",
"vigilant",
"vigorous",
"virulence",
"ward wrecker",
"weakness",
"well trained",
"windstorm",
"windstorm trained",
"windstorm trained",
"wise"
*/